In [1]:
from pandas import DataFrame
import numpy as np

In [2]:
df1 = DataFrame(np.zeros((3,3), int), index=['one','two','three'])
df1

       0  1  2
one    0  0  0
two    0  0  0
three  0  0  0

In [3]:
df2 = df1 + 3
df2

       0  1  2
one    3  3  3
two    3  3  3
three  3  3  3

In [ ]:
numpy로 4행 4열짜리 1로 채워진 배열 만들기, index=one, two,three,four
df3 = DataFrame()